package net.FatCactis.smoothparticles;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.particle.DefaultParticleType;
import net.minecraft.particle.ParticleEffect;
import net.minecraft.particle.ParticleType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class SmoothParticles implements ModInitializer {
	public static final String MOD_ID = "smoothparticles";

	public static final DefaultParticleType SAUL = FabricParticleTypes.simple();

	public static final DefaultParticleType GREEN_FLAME = FabricParticleTypes.simple();
	public static final DefaultParticleType ANGRY = FabricParticleTypes.simple();
	public static final DefaultParticleType ENCH_HIT = FabricParticleTypes.simple();
	public static final DefaultParticleType FLAME = FabricParticleTypes.simple();
	public static final DefaultParticleType EMERALD = FabricParticleTypes.simple();
	public static final DefaultParticleType HEART = FabricParticleTypes.simple();
	public static final DefaultParticleType LAVA = FabricParticleTypes.simple();
	public static final DefaultParticleType CONDUIT = FabricParticleTypes.simple();
	public static final DefaultParticleType STONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DIORITE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType ANDESITE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType GRANITE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType CALCITE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType TUFF_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DRIPSTONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DIRT_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType GRASS_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType COARSE_DIRT_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType MUD_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType NETHERRACK_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType CRIMSON_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType WARPED_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType COBBLESTONE_PIECE1 = FabricParticleTypes.simple();
	public static final DefaultParticleType COBBLESTONE_PIECE2 = FabricParticleTypes.simple();
	public static final DefaultParticleType COBBLESTONE_PIECE3 = FabricParticleTypes.simple();
	public static final DefaultParticleType OAK_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType SPRUCE_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType BIRCH_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType JUNGLE_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType ACACIA_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType DARK_OAK_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType MANGROVE_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType CRIMSON_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType WARPED_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType BEDROCK_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType SAND_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_SAND_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType GRAVEL_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType COAL_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType RAW_IRON_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType COPPER_PEBBLE_ORANGE = FabricParticleTypes.simple();
	public static final DefaultParticleType COPPER_PEBBLE_ORANGE_GREEN = FabricParticleTypes.simple();
	public static final DefaultParticleType COPPER_PEBBLE_GREEN = FabricParticleTypes.simple();
	public static final DefaultParticleType GOLD_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType REDSTONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType EMERALD_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType LAPIS_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DIAMOND_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType QUARTZ_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEBRIS_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType AMETHYST_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType IRON_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType NETHERITE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType OAK_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType BIRCH_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType SPRUCE_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType JUNGLE_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType ACACIA_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType DARK_OAK_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType MANGROVE_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType CRIMSON_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType WARPED_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType OAK_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType BIRCH_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType SPRUCE_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType JUNGLE_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType ACACIA_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType DARK_OAK_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType MANGROVE_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType AZALEA_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType SPONGE_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType GLASS_SHARD = FabricParticleTypes.simple();
	public static final DefaultParticleType SANDSTONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType COBWEB = FabricParticleTypes.simple();
	public static final DefaultParticleType STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType YELLOW_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType ORANGE_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType MAGENTA_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_BLUE_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType LIME_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType PINK_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType GRAY_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_GRAY_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType CYAN_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType PURPLE_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType BLUE_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType BROWN_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType GREEN_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType BLACK_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType SMOOTH_STONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType BRICK = FabricParticleTypes.simple();
	public static final DefaultParticleType MUD_BRICK = FabricParticleTypes.simple();
	public static final DefaultParticleType NETHER_BRICK = FabricParticleTypes.simple();
	public static final DefaultParticleType PURPUR_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType PRISMARINE_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType DARK_PRISMARINE_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType END_STONE_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_NETHER_BRICK = FabricParticleTypes.simple();
	public static final DefaultParticleType BLACKSTONE_PEBBLE = FabricParticleTypes.simple();
	public static final DefaultParticleType HONEYCOMB = FabricParticleTypes.simple();
	public static final DefaultParticleType ICE_CUBE = FabricParticleTypes.simple();
	public static final DefaultParticleType SNOWBALL = FabricParticleTypes.simple();
	public static final DefaultParticleType SLIMEBALL = FabricParticleTypes.simple();
	public static final DefaultParticleType CLAY_BALL = FabricParticleTypes.simple();
	public static final DefaultParticleType JUKEBOX = FabricParticleTypes.simple();
	public static final DefaultParticleType PUMPKIN = FabricParticleTypes.simple();
	public static final DefaultParticleType BASALT = FabricParticleTypes.simple();
	public static final DefaultParticleType SMOOTH_BASALT = FabricParticleTypes.simple();
	public static final DefaultParticleType BRIGHT_GLOWSTONE = FabricParticleTypes.simple();
	public static final DefaultParticleType DARK_GLOWSTONE = FabricParticleTypes.simple();
	public static final DefaultParticleType PACKED_MUD = FabricParticleTypes.simple();
	public static final DefaultParticleType BROWN_MUSHROOM = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_MUSHROOM = FabricParticleTypes.simple();
	public static final DefaultParticleType MUSHROOM_STEM = FabricParticleTypes.simple();
	public static final DefaultParticleType MYCELIUM = FabricParticleTypes.simple();
	public static final DefaultParticleType SCULK_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType BONE_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType WHITE_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType ORANGE_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType MAGENTA_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_BLUE_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType YELLOW_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIME_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType PINK_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType GRAY_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_GRAY_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType CYAN_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType PURPLE_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType BROWN_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType BLUE_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType GREEN_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType BLACK_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType HAY_BALE = FabricParticleTypes.simple();
	public static final DefaultParticleType TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType EIGHTH_NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType BEAMED_EIGHTH_NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType WHOLE_NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType HALF_NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType QUARTER_NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType DRIED_KELP = FabricParticleTypes.simple();
	public static final DefaultParticleType SHROOMLIGHT = FabricParticleTypes.simple();
	public static final DefaultParticleType FROGLIGHT_MIDDLE = FabricParticleTypes.simple();
	public static final DefaultParticleType OCHRE_FROGLIGHT = FabricParticleTypes.simple();
	public static final DefaultParticleType VERDANT_FROGLIGHT = FabricParticleTypes.simple();
	public static final DefaultParticleType PEARLESCENT_FROGLIGHT = FabricParticleTypes.simple();
	public static final DefaultParticleType CHERRY_BARK = FabricParticleTypes.simple();
	public static final DefaultParticleType COBBLED_DEEPSLATE = FabricParticleTypes.simple();
	public static final DefaultParticleType POLISHED_ANDESITE = FabricParticleTypes.simple();
	public static final DefaultParticleType POLISHED_DIORITE = FabricParticleTypes.simple();
	public static final DefaultParticleType POLISHED_GRANITE = FabricParticleTypes.simple();
	public static final DefaultParticleType PODZOL = FabricParticleTypes.simple();
	public static final DefaultParticleType POLISHED_DEEPSLATE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_COAL = FabricParticleTypes.simple();
	public static final DefaultParticleType COPPER_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_COPPER_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_EMERALD_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_GOLD_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_IRON_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_REDSTONE_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType EMERALD_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType GOLD_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType REDSTONE_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType BUDDING_AMETHYST = FabricParticleTypes.simple();
	public static final DefaultParticleType COAL_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType COPPER_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType DIAMOND_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_DIAMOND_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType DEEPSLATE_LAPIS_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType LAPIS_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType NETHER_GOLD_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType NETHER_QUARTZ_ORE = FabricParticleTypes.simple();
	public static final DefaultParticleType IRON_PIECE = FabricParticleTypes.simple();
	public static final DefaultParticleType RAW_GOLD = FabricParticleTypes.simple();
	public static final DefaultParticleType RAW_COPPER = FabricParticleTypes.simple();
	public static final DefaultParticleType BAMBOO_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType BAMBOO_PLANKS = FabricParticleTypes.simple();
	public static final DefaultParticleType BOOK1 = FabricParticleTypes.simple();
	public static final DefaultParticleType BOOK2 = FabricParticleTypes.simple();
	public static final DefaultParticleType BOOK3 = FabricParticleTypes.simple();
	public static final DefaultParticleType BOOKSHELF = FabricParticleTypes.simple();
	public static final DefaultParticleType CHERRY_LEAF = FabricParticleTypes.simple();
	public static final DefaultParticleType CHERRY_SPLINTER = FabricParticleTypes.simple();
	public static final DefaultParticleType DEAD_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType EXPOSED_COPPER = FabricParticleTypes.simple();
	public static final DefaultParticleType BIG_BONE_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType MAGMA_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType NOTE = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_SANDSTONE = FabricParticleTypes.simple();
	public static final DefaultParticleType TNT1 = FabricParticleTypes.simple();
	public static final DefaultParticleType TNT2 = FabricParticleTypes.simple();
	public static final DefaultParticleType WHITE_STRING = FabricParticleTypes.simple();
	public static final DefaultParticleType BLACK_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType BLUE_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType BROWN_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType CYAN_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType GRAY_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType GREEN_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_BLUE_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_GRAY_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType LIME_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType MAGENTA_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType ORANGE_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType PINK_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType PURPLE_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType WHITE_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType YELLOW_GLAZED_TERRACOTTA = FabricParticleTypes.simple();
	public static final DefaultParticleType TUBE_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType FIRE_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType HORN_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType BUBBLE_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType BRAIN_CORAL = FabricParticleTypes.simple();
	public static final DefaultParticleType SPAWNER = FabricParticleTypes.simple();
	public static final DefaultParticleType COMMAND_BLOCK = FabricParticleTypes.simple();
	public static final DefaultParticleType BLACK_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType BLUE_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType BROWN_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType CYAN_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType GRAY_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType GREEN_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_GRAY_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType LIME_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType MAGENTA_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType ORANGE_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType PINK_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType PURPLE_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType RED_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType WHITE_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType YELLOW_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType LIGHT_BLUE_CONCRETE = FabricParticleTypes.simple();
	public static final DefaultParticleType SPORE_BLOSSOM = FabricParticleTypes.simple();
	public static final DefaultParticleType WEATHERED_COPPER = FabricParticleTypes.simple();

	@Override
	public void onInitialize() {
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "angry"), ANGRY);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "enchanted_hit"), ENCH_HIT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "flame"), FLAME);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "glint"), EMERALD);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "heart"), HEART);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lava"), LAVA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "nautilus"), CONDUIT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "saul"), SAUL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "green_flame"), GREEN_FLAME);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "stone_pebble"), STONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "diorite_pebble"), DIORITE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "granite_pebble"), GRANITE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "andesite_pebble"), ANDESITE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_pebble"), DEEPSLATE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "calcite_pebble"), CALCITE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "tuff_pebble"), TUFF_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dripstone_pebble"), DRIPSTONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dirt_pebble"), DIRT_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "grass_piece"), GRASS_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "coarse_dirt_pebble"), COARSE_DIRT_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mud_piece"), MUD_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "netherrack_pebble"), NETHERRACK_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "crimson_piece"), CRIMSON_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "warped_piece"), WARPED_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cobblestone_pebble1"), COBBLESTONE_PIECE1);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cobblestone_pebble2"), COBBLESTONE_PIECE2);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cobblestone_pebble3"), COBBLESTONE_PIECE3);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "oak_splinter"), OAK_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "birch_splinter"),BIRCH_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "spruce_splinter"), SPRUCE_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "jungle_splinter"), JUNGLE_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "acacia_splinter"), ACACIA_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dark_oak_splinter"), DARK_OAK_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mangrove_splinter"), MANGROVE_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "crimson_splinter"), CRIMSON_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "warped_splinter"), WARPED_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bedrock_pebble"), BEDROCK_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "sand_piece"), SAND_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_sand_piece"), RED_SAND_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gravel_piece"), GRAVEL_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "coal_pebble"), COAL_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "raw_iron_pebble"), RAW_IRON_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "copper_pebble_orange"), COPPER_PEBBLE_ORANGE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "copper_pebble_orange_green"), COPPER_PEBBLE_ORANGE_GREEN);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "copper_pebble_green"), COPPER_PEBBLE_GREEN);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gold_pebble"), GOLD_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "redstone_pebble"), REDSTONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "emerald_pebble"), EMERALD_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lapis_pebble"), LAPIS_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "diamond_pebble"), DIAMOND_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "quartz_pebble"), QUARTZ_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "debris_pebble"), DEBRIS_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "amethyst_pebble"), AMETHYST_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "iron_pebble"), IRON_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "netherite_pebble"), NETHERITE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "oak_bark"), OAK_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "birch_bark"), BIRCH_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "spruce_bark"), SPRUCE_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "jungle_bark"), JUNGLE_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "acacia_bark"), ACACIA_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dark_oak_bark"), DARK_OAK_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mangrove_bark"), MANGROVE_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "crimson_bark"), CRIMSON_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "warped_bark"), WARPED_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "oak_leaf"), OAK_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "birch_leaf"), BIRCH_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "spruce_leaf"), SPRUCE_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "jungle_leaf"), JUNGLE_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "acacia_leaf"), ACACIA_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dark_oak_leaf"), DARK_OAK_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mangrove_leaf"), MANGROVE_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "azalea_leaf"), AZALEA_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "sponge_piece"), SPONGE_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "glass_shard"), GLASS_SHARD);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "sandstone_pebble"), SANDSTONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cobweb"), COBWEB);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "string"), STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_string"), RED_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "yellow_string"), YELLOW_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "orange_string"), ORANGE_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "magenta_string"), MAGENTA_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_blue_string"), LIGHT_BLUE_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lime_string"), LIME_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pink_string"), PINK_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gray_string"), GRAY_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_gray_string"), LIGHT_GRAY_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cyan_string"), CYAN_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "purple_string"), PURPLE_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "blue_string"), BLUE_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brown_string"), BROWN_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "green_string"), GREEN_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "black_string"), BLACK_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "smooth_stone_pebble"), SMOOTH_STONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brick"), BRICK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mud_brick"), MUD_BRICK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "nether_brick"), NETHER_BRICK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "purpur_piece"), PURPUR_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "prismarine_piece"), PRISMARINE_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dark_prismarine_piece"), DARK_PRISMARINE_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "end_stone_piece"), END_STONE_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_nether_brick"), RED_NETHER_BRICK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "blackstone_pebble"), BLACKSTONE_PEBBLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "honeycomb"), HONEYCOMB);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "ice_cube"), ICE_CUBE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "snowball"), SNOWBALL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "slimeball"), SLIMEBALL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "clay_ball"), CLAY_BALL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "jukebox"), JUKEBOX);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pumpkin"), PUMPKIN);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "basalt"), BASALT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "smooth_basalt"), SMOOTH_BASALT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bright_glowstone"), BRIGHT_GLOWSTONE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dark_glowstone"), DARK_GLOWSTONE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "packed_mud"), PACKED_MUD);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brown_mushroom"), BROWN_MUSHROOM);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_mushroom"), RED_MUSHROOM);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mushroom_stem"), MUSHROOM_STEM);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "mycelium"), MYCELIUM);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "sculk_block"), SCULK_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bone_block"), BONE_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "white_terracotta"), WHITE_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "orange_terracotta"), ORANGE_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "magenta_terracotta"), MAGENTA_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_blue_terracotta"), LIGHT_BLUE_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "yellow_terracotta"), YELLOW_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lime_terracotta"), LIME_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pink_terracotta"), PINK_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gray_terracotta"), GRAY_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_gray_terracotta"), LIGHT_GRAY_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cyan_terracotta"), CYAN_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "purple_terracotta"), PURPLE_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brown_terracotta"), BROWN_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "blue_terracotta"), BLUE_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "green_terracotta"), GREEN_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_terracotta"), RED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "black_terracotta"), BLACK_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "hay_bale"), HAY_BALE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "terracotta"), TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "eighth_note"), EIGHTH_NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "beamed_eighth_note"), BEAMED_EIGHTH_NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "whole_note"), WHOLE_NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "half_note"), HALF_NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "quarter_note"), QUARTER_NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dried_kelp"), DRIED_KELP);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "shroomlight"), SHROOMLIGHT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "froglight_middle"), FROGLIGHT_MIDDLE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "ochre_froglight"), OCHRE_FROGLIGHT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "verdant_froglight"), VERDANT_FROGLIGHT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pearlescent_froglight"), PEARLESCENT_FROGLIGHT);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cherry_bark"), CHERRY_BARK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cobbled_deepslate"), COBBLED_DEEPSLATE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "polished_andesite_pebble"), POLISHED_ANDESITE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "polished_diorite_pebble"), POLISHED_DIORITE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "polished_granite_pebble"), POLISHED_GRANITE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "podzol"), PODZOL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "polished_deepslate"), POLISHED_DEEPSLATE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_coal"), DEEPSLATE_COAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "copper_ore"), COPPER_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_copper_ore"), DEEPSLATE_COPPER_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_emerald_ore"), DEEPSLATE_EMERALD_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_gold_ore"), DEEPSLATE_GOLD_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_iron_ore"), DEEPSLATE_IRON_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_redstone_ore"), DEEPSLATE_REDSTONE_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "emerald_ore"), EMERALD_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gold_ore"), GOLD_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "redstone_ore"), REDSTONE_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "budding_amethyst"), BUDDING_AMETHYST);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "coal_block"), COAL_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "diamond_ore"), DIAMOND_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_diamond_ore"), DEEPSLATE_DIAMOND_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "deepslate_lapis_ore"), DEEPSLATE_LAPIS_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lapis_ore"), LAPIS_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "nether_gold_ore"), NETHER_GOLD_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "nether_quartz_ore"), NETHER_QUARTZ_ORE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "iron_piece"), IRON_PIECE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "raw_gold"), RAW_GOLD);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "raw_copper"), RAW_COPPER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "copper_block"), COPPER_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bamboo_planks"), BAMBOO_PLANKS);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bamboo_block"), BAMBOO_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "book1"), BOOK1);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "book2"), BOOK2);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "book3"), BOOK3);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bookshelf"), BOOKSHELF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cherry_leaf"), CHERRY_LEAF);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cherry_splinter"), CHERRY_SPLINTER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "dead_coral"), DEAD_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "exposed_copper"), EXPOSED_COPPER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "big_bone_block"), BIG_BONE_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "magma_block"), MAGMA_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "note"), NOTE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_sandstone"), RED_SANDSTONE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "tnt1"), TNT1);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "tnt2"), TNT2);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "white_string"), WHITE_STRING);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "black_glazed_terracotta"), BLACK_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "blue_glazed_terracotta"), BLUE_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brown_glazed_terracotta"), BROWN_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cyan_glazed_terracotta"), CYAN_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gray_glazed_terracotta"), GRAY_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "green_glazed_terracotta"), GREEN_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_blue_glazed_terracotta"), LIGHT_BLUE_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_gray_glazed_terracotta"), LIGHT_GRAY_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lime_glazed_terracotta"), LIME_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "magenta_glazed_terracotta"), MAGENTA_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_glazed_terracotta"), RED_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "orange_glazed_terracotta"), ORANGE_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pink_glazed_terracotta"), PINK_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "purple_glazed_terracotta"), PURPLE_GLAZED_TERRACOTTA);
//		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_glazed_terracotta"), RED_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "white_glazed_terracotta"), WHITE_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "yellow_glazed_terracotta"), YELLOW_GLAZED_TERRACOTTA);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "tube_coral"), TUBE_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "fire_coral"), FIRE_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "horn_coral"), HORN_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "bubble_coral"), BUBBLE_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brain_coral"), BRAIN_CORAL);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "spawner"), SPAWNER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "command_block"), COMMAND_BLOCK);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "black_concrete"), BLACK_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "blue_concrete"), BLUE_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "brown_concrete"), BROWN_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "cyan_concrete"), CYAN_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "gray_concrete"), GRAY_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "green_concrete"), GREEN_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_gray_concrete"), LIGHT_GRAY_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "lime_concrete"), LIME_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "magenta_concrete"), MAGENTA_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "pink_concrete"), PINK_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "purple_concrete"), PURPLE_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "red_concrete"), RED_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "white_concrete"), WHITE_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "yellow_concrete"), YELLOW_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "light_blue_concrete"), LIGHT_BLUE_CONCRETE);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "spore_blossom"), SPORE_BLOSSOM);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "weathered_copper"), WEATHERED_COPPER);
		Registry.register(Registries.PARTICLE_TYPE, new Identifier(MOD_ID, "orange_concrete"), ORANGE_CONCRETE);
	}
}